### ISSUE TITLE
How Do I install this code????

### ISSUE THREAD

**Issue by Peter-Schorn** [jakehilborn/displayplacer#18]
First of all, which files do I download? I see multiple download links scattered across the webpage, and  I'm not sure what I need to download. Next, how do I install the software? Finally, what commands do I enter if I want to toggle the main display between my macbook's internal display and my external monitor? **I have absoultely no experience coding**, so I have no idea what I'm doing here. 

EDIT: I think I installed the software. However, when I enter `displayplacer list` into terminal as a test command, it says `zsh: command not found: displayplacer`

Please walk me through this from the VERY beginning.

**Comment by jakehilborn** [comment]
For posterity here are the instructions.

If using homebrew: Open a terminal and type `brew tap jakehilborn/jakehilborn && brew install displayplacer` and hit enter to install displayplacer. Now, type `displayplacer` and hit enter for instructions.

If not using homebrew, open the [releases](https://github.com/jakehilborn/displayplacer/releases) tab and click the displayplacer link under the latest version. 
![image](https://user-images.githubusercontent.com/5554178/69909151-92b6a480-13ab-11ea-91c5-50d0c4f9ac16.png)  
to download the displayplacer executable. Open a terminal and type in `cd ~/Downloads` and hit enter to change directory to the downloads folder. Then, type in `chmod +x displayplacer` and hit enter to change the mode of the file to make it executable. Finally, type in `./displayplacer` and hit enter for usage instructions. Note, the instructions will tell you to execute `displayplacer` but since you downloaded the file directly and it's not in your path you'll actually need to provide the file path for the file. For example, `/Users/jake/Downloads/displayplacer`.

**Comment by douglassimaging** [comment]
Sorry also when the instructions come up it says to run displayplacer list but I can’t find displayplacer list. As I said I’m very very new at this
