### ISSUE TITLE
Command does not preserve scaling.

### ISSUE THREAD

**Issue by jmonroynieto** [jakehilborn/displayplacer#35]
I'm have used the tool for a few months to easily rotate my external monitor between 90 and 0. However, the resolution of my laptop display changes to the "more space" scaling setting every time. I've tried multiple commands with the correct resolutions but my system is not getting it.

it is switched to 1680x1050, I want it to stay at 1280x800.

I'll have to go back to the menu I am trying to avoid to solve this:

<img width="780" alt="Screen Shot 2020-06-05 at 11 58 14" src="https://user-images.githubusercontent.com/10119293/83913119-dd7ef380-a723-11ea-9698-7b4264b14739.png">

What can I do to retain scaling?

**Comment by crstauf** [comment]
I'm having a similar issue, where when I switch between portrait and landscape, scaling is set to "Default" rather than my preferred "More Space".

Here are the commands (with the monitor ID removed):

Landscape: `displayplacer "id: res:3200x1800 color_depth:8 scaling:on origin:(0,0) degree:0"`
Portrait: displayplacer "id: res:1800x3200 color_depth:8 scaling:on origin:(0,0) degree:90"`

Note: Changing `scaling:on` to `scaling:off` does not seem to do anything.

**Comment by crstauf** [comment]
Running the Landscape command a second time restores the scaling choice.

**Comment by varenc** [comment]
I am running into the same issue. It seems that passing `scaling:off` to displayplacer never works.  The resolution is always updated as if it's set to `scaling:on`.  It's my understanding that scaling on is basically "retina" mode where everything is actually rendered at double the logical resolution.

But there's a workaround. displayplacer can set `scaling:off` if you specify the desired configuration with the correct `mode:<N>` instead of just listing the desired properties.

Warning: displayplacer even sets `scaling:on` in very inappropriate situations and that might lead to mysterious performance issues.  For example, I have a 4K 3840x2160 display. When I use System Preferences to set my resolution to the native 3840x2160, macOS knows not to rendering this with "scaling on" since if my physical resolution is exactly my logical resolution there's no point in enabling Retina (scaling on).

However, if I try to do the same thing with displayplacer like this:
```
➜ displayplacer "id:722499605 res:3840x2160 hz:60 color_depth:8 scaling:off"
```

I end up with scaling/retina on.  This means that macOS is actually rendering everything at `7680x4320` resolution and then it's just being downscaled to for my monitor.  This leads to a very mysterious performance hit.  

To confirm this, here's what system_profile says about my display settings after a few different commands
```
➜ displayplacer "id:722499605 res:3840x2160 hz:60 color_depth:8 scaling:off"
➜ system_profiler SPDisplaysDataType  | grep -C1 Resolution
        DELL P2715Q:
          Resolution: 7680 x 4320 (8K UHD - 8K Ultra High Definition)                <--------- that's the problem
          UI Looks like: 3840 x 2160 @ 60 Hz
➜  displayplacer "id:722499605 mode:55"
➜  system_profiler SPDisplaysDataType  | grep -C1 Resolution
        DELL P2715Q:
          Resolution: 3840 x 2160 (2160p 4K UHD - Ultra High Definition)
          UI Looks like: 3840 x 2160 @ 60 H
```

**Comment by varenc** [comment]
Since explicitly passing in `scaling:off` to displayplacer doesn't work for me and can result in a subtle performance hit, I made a little bash script workaround around. Also helpful since mode numbers are not always consistent for the same physical screen.

```bash
function resolutionSwitch() {
  # check the output of `displayplacer list` and pass in everything after the "mode xx: " of the desired settings shown
  # if you want "scaling:off", just don't include scaling and pass in '$' at the end to match against the end
  # examples:
  #   resolutionSwitch "res:2304x1296 hz:60 color_depth:8$"
  #   resolutionSwitch "res:3008x1692 hz:60 color_depth:8 scaling:on"
  
  SID="2648EE53-5F1E-37A6-99FA-30FB0B2E49A9";     # my hardcoded the monitor ID
  ## Alternatively, get the screen id based on the monitor's description
  ## SID=$(displayplacer list | grep -B2 "27 inch external screen" | grep -i Persistent | awk '{print $4}')

  # extract the displayplacer mode number for the desired settings
  DESIRED="$1"
  MODE_NUM=$(displayplacer list | sed -E "s/[[:blank:]]+(<-- current mode)?$//g" | sed -n -e "/$SID/,/Persistent screen/ p"  | grep -E "^  mode" | grep "$DESIRED" | cut -d ":" -f 1 | sed -E 's/^[[:blank:]]+mode[[:blank:]]//g')

  # check that a single mode was found
  if [ $(echo $MODE_NUM | wc -w) -ne 1 ]; then 
    echo "Did not find a unique mode number: '$MODE_NUM'...giving up"; 
    return;
  fi
  
  echo "Switching monitor '$SID' to mode '$MODE_NUM' which represents the settings '$DESIRED'";
  displayplacer "id:$SID mode:$MODE_NUM"
}
```

Then use like this:

```console
$ resolutionSwitch "res:2304x1296 hz:60 color_depth:8$"
Switch monitor '2648EE53-5F1E-37A6-99FA-30FB0B2E49A9' to mode '181' which represents the settings 'res:2304x1296 hz:60 color_depth:8$'

$ resolutionSwitch "res:3008x1692 hz:60 color_depth:8 scaling:on"
Switch monitor '2648EE53-5F1E-37A6-99FA-30FB0B2E49A9' to mode '49' which represents the settings 'res:3008x1692 hz:60 color_depth:8 scaling:on'
```
